name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check repo files
        run: |
          ls
          test -f README.md
          test -f docker-compose.yml